apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hello-eks-cluster
  region: eu-west-2

accessConfig:
  authenticationMode: API_AND_CONFIG_MAP

managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: true
